### ISSUE TITLE
As a User, when I click the "Popular" Tab an Error is Displayed

### ISSUE THREAD

**Issue by kenmazaika** [austinarchibald/bloccit#1]
Hey Austin -

Looks like your bloccit app has a bug in it!  I just checked it out, and when I clicked on the popular button, linking me to [this URL](https://bloccit-austin.herokuapp.com/posts), I see the following error message:

![screen shot 2015-08-17 at 1 43 23 pm](https://cloud.githubusercontent.com/assets/233615/9311721/2ecb7204-44e6-11e5-8f6b-214bf0bc5453.png)

I ran the app on my local machine, and can't reproduce the problem.  Hopefully it's something easy, like just running the database migrations.  My hunch is that [this migration](https://github.com/austinarchibald/bloccit/blob/master/db/migrate/20150610214930_add_rank_to_posts.rb) didn't run.

Running the command:

```
heroku run rake db:migrate
```

Hopefully will fix it.  Hope this helps, Austin!  If this doesn't help, feel free to send me the error message in your heroku logs.  It could be a gnarly problem because you're using one database on localhost (sqlite) and a different one on production (postgres).  Using the same database across both generally makes it easier to do (this is called parity with a dev environment).  Developers generally agree that [it's a good thing](http://www.newmediacampaigns.com/blog/matching-development-production-environments).

Also, a quick plug for [Rollbar](http://rollbar.com), a free web app that you can use to send you email notifications when users (like me!) see errors (along with their full stack trace).  It's UI isn't as good as some of the other competitors out there (I'm thinking Airbrake here), but it has a free tier so it's a good plan to start.

Cheers,
Ken

**Comment by austinarchibald** [comment]
You are so right! Thank you. I ran the migration and it now loads. Thanks for the find! And I totally agree about running the same database. Firehose always did that, and I've been doing that with my latest projects. You guys are great. Hope all is well!

**Comment by kenmazaika** [comment]
Solid, Austin!  Glad that got it squared away!  Stay awesome!
